### ISSUE TITLE
Error: Cannot find module 'wrappy'

### ISSUE THREAD

**Issue by frapaa** [strabu/generator-kingbolt#2]
In a fresh project, when running `gulp install`the following error occurred:

```
Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Any tips? Thanks!

Using OS X 10.10 btw, if that matters..

**Comment by frapaa** [comment]
I tried `npm install wrappy` which solved this, but gave me similar errors for `clone` and `lodash._isnative`

**Comment by strabu** [comment]
hi,

thanks for sharing this issue.

Today I've tried generator-kingbolt V0.2.0 on a mac with OS X 10.10.1 and haven't got any errors when running gulp install.
Maybe something went wrong while running: "npm install" the first time.
Sometimes I'm getting errors and I run it a 2nd time to make things work - probably network issues in my case.
Could you please try the whole thing again with a new project in a new folder to see if it was a one-time experience?

If you are experiencing problems with the Karma-PhantomJS-Launcher on the Mac - these are definitely confirmed, I'll try to fix that.

**Comment by frapaa** [comment]
Looks like a ```brew update```solved the issue.. Thanks for helping!

**Comment by reddynr** [comment]
Hi,

I am getting below error while execute npm run. Please advice. Thanks

 mcac_client@1.0.0 dev C:\Users\xyz\WebstormProjects\Client
> nodemon server.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\narani\WebstormProjects\Client\node_modules\nodemo
n\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\n
ode_modules\got\node_modules\duplexify\node_modules\end-of-stream\node_modules\once\on
ce.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_m
odules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! mcac_client@1.0.0 dev: `nodemon server.js`

**Comment by reddynr** [comment]
Thank you people.

I solved the issue by install these packages

npm install -g wrappy

npm install process-nextick-args

**Comment by centigrade-thomas-becker** [comment]
I don't use generator-kingbolt, but out of the blue one of my builds is failing with `Error: Cannot find module 'wrappy'`.

@reddynr: Did you also update npm lately?
